### ISSUE TITLE
Missing test dependency

### ISSUE THREAD

**Issue by Gbury** [c-cube/iter#14]
Seems like some dependencies for the `build-test` opam target are not listed, for instance ` qcheck`. This breaks the build when `OPAMBUILDTEST=true`.

**Comment by c-cube** [comment]
Two options:

- maybe we can upgrade opam (it's probably an old one, right?)
- or: use opam to install dependencies only, then build tests manually

**Comment by Gbury** [comment]
Isn't it as simple as having the following deps ?
``` 
depends: [
  "ocamlfind"
  "base-bytes"
  "ocamlbuild" {build}
  "qcheck" {test}
]
```
