### ISSUE TITLE
Can't run tests with OUnit2 and qcheck-0.13

### ISSUE THREAD

**Issue by RiderALT** [c-cube/iter#29]
OUnit2 now is repalcement for OUnit.
[builder@localhost ocaml-iter-1.2.1]$ make test
Done: 53/58 (jobs: 1)File "qtest/run_qtest.ml", line 3, characters 5-11:
3 | open OUnit2;;
         ^^^^^^
Error: Unbound module OUnit2
Hint: Did you mean Unit?
      ocamlc qtest/.run_qtest.eobjs/byte/run_qtest.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -a+8 -safe-string -w -33 -g -bin-annot -I qtest/.run_qtest.eobjs/byte -I /usr/lib64/ocaml/bytes -I /usr/lib64/ocaml/qcheck-core -I /usr/lib64/ocaml/result -I src/.iter.objs/byte -I src/.iter.objs/native -no-alias-deps -opaque -o qtest/.run_qtest.eobjs/byte/run_qtest.cmo -c -impl qtest/run_qtest.ml)
make: *** [Makefile:8: test] Error 1

after correcting the qtest/dune, the error looks like this:
ocaml-iter-1.2.1]$ make test
Done: 53/58 (jobs: 1)File "../src/Iter.ml", line 32, characters 5-7:
Error: This pattern matches values of type unit
       but a pattern was expected which matches values of type test_ctxt
      ocamlc qtest/.run_qtest.eobjs/byte/run_qtest.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -a+8 -safe-string -w -33 -g -bin-annot -I qtest/.run_qtest.eobjs/byte -I /usr/lib64/ocaml/bytes -I /usr/lib64/ocaml/ounit2 -I /usr/lib64/ocaml/ounit2/advanced -I /usr/lib64/ocaml/qcheck-core -I /usr/lib64/ocaml/result -I src/.iter.objs/byte -I src/.iter.objs/native -no-alias-deps -opaque -o qtest/.run_qtest.eobjs/byte/run_qtest.cmo -c -impl qtest/run_qtest.ml)
make: *** [Makefile:8: test] Error 1

**Comment by c-cube** [comment]
This should be opened in [qtest](https://github.com/vincent-hugot/qtest) rather than here, I think. Why is using `ounit` bad anyway?
