### ISSUE TITLE
Iter.IO.write_lines with "empty" iter still writes a newline char to output file

### ISSUE THREAD

**Issue by mooreryan** [c-cube/iter#38]
Not sure if this is a bug or intended behavior, but on an "empty" iter, the `write_lines` function will write a newline to the output file, rather than writing nothing.  

But here is a simplified example of what's happening.  The snoc/intersperse bit is from the `write_bytes_line` function which is called by `write_lines` ([here](https://github.com/c-cube/iter/blob/29ece562e2a1d4e62ca286ffd5af356851ab5bf5/src/Iter.ml#L1210)).

```ocaml
# let i = Iter.of_list [] in Iter.snoc (Iter.intersperse "\n" i) "\n" |> Iter.to_list;;
- : string list = ["\n"]

# let i = Iter.of_list ["a"] in Iter.snoc (Iter.intersperse "\n" i) "\n" |> Iter.to_list;;
- : string list = ["a"; "\n"]

# let i = Iter.of_list ["a"; "b"] in Iter.snoc (Iter.intersperse "\n" i) "\n" |> Iter.to_list;;
- : string list = ["a"; "\n"; "b"; "\n"]
```

My expectation was that for an empty iter, nothing would be written to the file, but instead a newline is written. Is this the intended behavior?

**Comment by c-cube** [comment]
It's always tricky to deal with newlines, but I think this qualifies as a bug. Let me try for a fix.

**Comment by c-cube** [comment]
please test :)

**Comment by mooreryan** [comment]
Thanks for taking a look.  I pinned your [wip-38](https://github.com/c-cube/iter/tree/wip-38) branch, and it seems to work fine for me, thanks.
